### PR TITLE
S16mcu fixes (#174)

### PR DESCRIPTION
**Pull request by gyurco**
Fix i8751 games, add Quartet controls.

Still an issue: boot screen is flipped. Maybe i8255's reset values should be changed?

### CODE REVIEW

**Comment by jotego** [comment]
Thank you. It looks good overall but the complexity of resetting the MCU memory should be part of the MCU module and not handled over to the core. So the _jtframe_8751mcu_ port interfacte can be kept constant. That way the other cores using this won't see the change. Also the idea of all these wrappers is to make design easy, and passing the reset task a level above goes against that principle. I suggest these changes:

- keep the old _jtframe_8751mcu_ port interface
- make a new _jtframe_ram_rst_ module, with the _jtframe_ram_ interface plus a _rst_ pin
- include the reset logic inside that module
- restore the files for other cores (biocom, btiger,cop,karnov,s16b,sf) 

That way, changes to all modules, including 8751mcu itself, are minimized. The new _jtfame_ram_rst_ module will be useful in other cases and easy to swap with the regular _jtframe_ram_ module. This will also automatically add the functionality to the other cores, which could be sensitive to this issue too.

Thank you, it is going to be a good new feature for the MCU

**Comment by gyurco** [comment]
IMHO the current method is more versatile, as you can fill with arbitrary data, or just inject one byte to RAM.

But there's a bigger concern: if I put the reset logic into the MCU, I cannot control when the external reset is released, and that would be a problem if the MCU should be run, but the RAM is still in clearing phase.

**Comment by jotego** [comment]
The reset is held during all the ROM download time, which is very long in comparison to the RAM length. There is a minimum time for user-triggered resets too. I will check how long it is.

I see your point about versatility but I think the right tradeoff is for game-module simplicity.

**Comment by gyurco** [comment]
Here's more important to reset the RAM when the 'reset' option is chosen in OSD (or by button). When loading the core, the BRAM is initialized to 0 anyway.

**Comment by jotego** [comment]
> Here's more important to reset the RAM when the 'reset' option is chosen in OSD (or by button). When loading the core, the BRAM is initialized to 0 anyway.

Yes, jtframe_board controls the length of that reset

**Comment by jotego** [comment]
Another option is to make the 128 bytes available from non-BRAM memory, so reset acts on a single clock cycle. The original memory may have been like that. In that case, there is no need for a reset address counter.

**Comment by gyurco** [comment]
That's 1024 registers  + other logic, I think it's too much.

Adding automatic BRAM reset would need to test all other cores which use it, sorry, but I'm a bit reluctant to do it. The current reset logic is only +4 lines, and works well so far.

**Comment by jotego** [comment]
I'll change it myself then.

**Comment by gyurco** [comment]
> I'll change it myself then.

Your repo, your choice.
I just genuinely think that:
- It causes more problems than it solves.
- Only one core required it so far, thus there's no benefit yet from the generalization.

**Comment by jotego** [comment]
No problem. Thanks for fixing the bug!

**Pull request merged**
