### PR TITLE
Outrun: use a lfbuf in SDRAM for SiDi128

### PR DESCRIPTION
**Pull request by gyurco**

### CODE REVIEW

**Comment by jotego** [comment]
Thank you!

**Comment by gyurco** [comment]
Maybe you can delete the branches created by me, I don't have the rights to do it.

**Comment by jotego** [comment]
I just did. Thanks for asking. I cannot assign better permissions without converting this account to an organization. I'd rather not do that yet.

**Comment by gyurco** [comment]
I don't know if something changed or I was just ignorant, but I was able to delete all my remaining branches. Probably it will work in the future(?)

**Pull request merged**
